
import React, { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";
import { FileText, Send, Mic, Brain } from "lucide-react";
import { askHealthQuestion } from "@/services/healthAIService";
import VoiceInput from "./VoiceInput";

const GeminiHealthAdvisor = () => {
  const [question, setQuestion] = useState("");
  const [response, setResponse] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [voiceInputOpen, setVoiceInputOpen] = useState(false);

  const handleQuestionSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!question.trim()) {
      toast.error("Please enter a question");
      return;
    }

    setIsLoading(true);
    setResponse("");

    try {
      const answer = await askHealthQuestion(question);
      setResponse(answer);
      toast.success("Response received");
    } catch (error) {
      console.error("Error:", error);
      toast.error("Failed to get response. Please try again.");
      setResponse("Sorry, there was an error processing your question. Please try again later.");
    } finally {
      setIsLoading(false);
    }
  };

  const handleVoiceInput = (transcript: string) => {
    setQuestion(transcript);
    setVoiceInputOpen(false);
  };

  return (
    <div className="space-y-4">
      <Card className="medical-card">
        <CardHeader className="bg-gradient-to-r from-indigo-500 to-purple-600 text-white rounded-t-xl">
          <CardTitle className="flex items-center gap-2">
            <Brain className="h-6 w-6" />
            <span>AI Health Advisor</span>
          </CardTitle>
        </CardHeader>
        <CardContent className="pt-4">
          <form onSubmit={handleQuestionSubmit} className="space-y-4">
            <div className="flex space-x-2">
              <Input
                placeholder="Ask a health question..."
                value={question}
                onChange={(e) => setQuestion(e.target.value)}
                className="flex-grow"
              />
              <Button 
                type="button" 
                variant="outline"
                onClick={() => setVoiceInputOpen(true)}
              >
                <Mic className="h-5 w-5" />
              </Button>
              <Button type="submit" disabled={isLoading}>
                {isLoading ? (
                  <div className="flex items-center gap-2">
                    <div className="h-4 w-4 animate-spin rounded-full border-2 border-t-transparent"></div>
                    <span>Processing...</span>
                  </div>
                ) : (
                  <div className="flex items-center gap-1">
                    <Send className="h-4 w-4" />
                    <span>Send</span>
                  </div>
                )}
              </Button>
            </div>
          </form>

          {response && (
            <div className="mt-6 space-y-2">
              <div className="flex items-center gap-2 text-lg font-semibold text-primary">
                <FileText className="h-5 w-5" />
                <h3>AI Response</h3>
              </div>
              <div className="whitespace-pre-wrap rounded-md bg-muted p-4 text-foreground">
                {response}
              </div>
            </div>
          )}

          <div className="mt-4 text-xs text-muted-foreground">
            <p>
              Powered by AI. Responses are generated by AI and should not replace professional medical advice.
              Always consult with a healthcare professional for medical concerns.
            </p>
          </div>
        </CardContent>
      </Card>

      <VoiceInput
        isOpen={voiceInputOpen}
        onClose={() => setVoiceInputOpen(false)}
        onTranscript={handleVoiceInput}
      />
    </div>
  );
};

export default GeminiHealthAdvisor;
